export const SIGNUP_LOADING = "SIGNUP_LOADING"
export const SIGNUP_SUCCESSFULL = "SIGNUP_SUCCESSFULL"
export const SIGNUP_FAILED = "SIGNUP_FAILED"
export const SIGNIN_LOADING = "SIGIN_LOADING"
export const SIGNIN_FAILED = "SIGNIN_FAILED"
export const SIGNIN_SUCCESSFULL = "SIGNIN_SUCCESSFULL"
export const AUTHENTICATE = "AUTHENTICATE";
export const UNAUTHENTICATE = "UNAUTHENTICATE";